name: Kiosk-front

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged

    strategy:
      matrix:
        node-version: [16.x]

    steps:
     - name: executing remote ssh commands using password
       if: github.event_name == 'pull_request'
       uses: appleboy/ssh-action@v0.1.4
       with:
           host: ${{ secrets.HOST }}
           port: ${{ secrets.PORT }}
           username: ${{ secrets.USERNAME }}
           password: ${{ secrets.PASSWORD }}
           script : |
              cd ${{ secrets.WEB_PATH }}
              git checkout main
              git pull origin main
              npm install 
              npm run build
              service nginx restart
